//notifications for errors
export const NOTIFY_SEND = 'NOTIFY_SEND';
export const NOTIFY_DISMISS = 'NOTIFY_DISMISS';
export const NOTIFY_CLEAR = 'NOTIFY_CLEAR';

//search books
export const FETCH_BOOKS_START = 'FETCH_BOOKS_START';
export const FETCH_BOOKS_SUCCESS =  'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAIL = 'FETCH_BOOKS_FAIL';

//favorite books
export const FETCH_USER_START = 'FETCH_USER_START';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';
export const FETCH_FAVORITE_BOOKS_START = 'FETCH_FAVORITE_BOOKS_START';
export const FETCH_FAVORITE_BOOKS_SUCCESS =  'FETCH_FAVORITE_BOOKS_SUCCESS';
export const FETCH_FAVORITE_BOOKS_FAIL = 'FETCH_FAVORITE_BOOKS_FAIL';
export const ADD_FAVORITE_BOOKS_START = 'ADD_FAVORITE_BOOKS_START';
export const ADD_FAVORITE_BOOKS_SUCCESS =  'ADD_FAVORITE_BOOKS_SUCCESS';
export const ADD_FAVORITE_BOOKS_FAIL = 'ADD_FAVORITE_BOOKS_FAIL';
export const DELETE_FAVORITE_BOOKS_START = 'DELETE_FAVORITE_BOOKS_START';
export const DELETE_FAVORITE_BOOKS_SUCCESS =  'DELETE_FAVORITE_BOOKS_SUCCESS';
export const DELETE_FAVORITE_BOOKS_FAIL = 'DELETE_FAVORITE_BOOKS_FAIL';